-- Generated by packages/schedule_rules/tool/generate_access_scenarios.dart.
-- Edit the JSON scenarios, then regenerate; do not edit this file directly.
begin;
create extension if not exists pgtap with schema extensions;
select plan(96);
insert into auth.users(id, email) values
  ('00000000-0000-0000-0000-000000000a02', 'access-scenario-maintainer@example.test');
insert into public.sections(id, name, display_order) values
  ('00000000-0000-0000-0000-000000000a04', 'Access scenario nights', 991),
  ('00000000-0000-0000-0000-000000000a05', 'Access scenario days', 992);
insert into private.maintainer_identity(auth_user_id) values ('00000000-0000-0000-0000-000000000a02');
-- plain Staff member
select set_config('request.jwt.claims', '{}', true);
insert into auth.users(id, email) values ('00000000-0000-0000-0000-000000000b00', 'access-scenario-0@example.test');
insert into public.staff_members(id, display_name, role, active)
  values ('00000000-0000-0000-0000-000000000c00', 'Access scenario 0', 'staff_member', true);
insert into public.staff_accounts
  (staff_member_id, auth_user_id, personal_email, accepted_invite_at)
  values ('00000000-0000-0000-0000-000000000c00', '00000000-0000-0000-0000-000000000b00', 'access-scenario-0@example.test', now());
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000b00","role":"authenticated"}', true);
set local role authenticated;
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a04'), false, 'plain Staff member: can_edit_section(nights)');
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a05'), false, 'plain Staff member: can_edit_section(days)');
select is(public.can_edit_schedule(), false, 'plain Staff member: can_edit_schedule');
select is(public.can_manage_staff(), false, 'plain Staff member: can_manage_staff');
select is(public.can_manage_unit(), false, 'plain Staff member: can_manage_unit');
select is(public.can_read_change_log(), false, 'plain Staff member: can_read_change_log');
select ok((select manager is not distinct from false from public.current_access()), 'plain Staff member: current_access.manager');
select ok((select administrator is not distinct from false from public.current_access()), 'plain Staff member: current_access.administrator');
select ok((select maintainer is not distinct from false from public.current_access()), 'plain Staff member: current_access.maintainer');
select ok((select staff_member_id is not distinct from '00000000-0000-0000-0000-000000000c00'::uuid from public.current_access()), 'plain Staff member: current_access.staff_member_id');
select ok((select night_scheduler_section_ids is not distinct from '{}'::uuid[] from public.current_access()), 'plain Staff member: current_access.night_scheduler_section_ids');
select is((select count(*)::integer from public.current_access()), 1, 'plain Staff member: one Access row');
reset role;
-- Manager
select set_config('request.jwt.claims', '{}', true);
insert into auth.users(id, email) values ('00000000-0000-0000-0000-000000000b01', 'access-scenario-1@example.test');
insert into public.staff_members(id, display_name, role, active)
  values ('00000000-0000-0000-0000-000000000c01', 'Access scenario 1', 'manager', true);
insert into public.staff_accounts
  (staff_member_id, auth_user_id, personal_email, accepted_invite_at)
  values ('00000000-0000-0000-0000-000000000c01', '00000000-0000-0000-0000-000000000b01', 'access-scenario-1@example.test', now());
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000b01","role":"authenticated"}', true);
set local role authenticated;
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a04'), true, 'Manager: can_edit_section(nights)');
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a05'), true, 'Manager: can_edit_section(days)');
select is(public.can_edit_schedule(), true, 'Manager: can_edit_schedule');
select is(public.can_manage_staff(), true, 'Manager: can_manage_staff');
select is(public.can_manage_unit(), true, 'Manager: can_manage_unit');
select is(public.can_read_change_log(), true, 'Manager: can_read_change_log');
select ok((select manager is not distinct from true from public.current_access()), 'Manager: current_access.manager');
select ok((select administrator is not distinct from false from public.current_access()), 'Manager: current_access.administrator');
select ok((select maintainer is not distinct from false from public.current_access()), 'Manager: current_access.maintainer');
select ok((select staff_member_id is not distinct from '00000000-0000-0000-0000-000000000c01'::uuid from public.current_access()), 'Manager: current_access.staff_member_id');
select ok((select night_scheduler_section_ids is not distinct from '{}'::uuid[] from public.current_access()), 'Manager: current_access.night_scheduler_section_ids');
select is((select count(*)::integer from public.current_access()), 1, 'Manager: one Access row');
reset role;
-- Administrator
select set_config('request.jwt.claims', '{}', true);
insert into auth.users(id, email) values ('00000000-0000-0000-0000-000000000b02', 'access-scenario-2@example.test');
insert into public.staff_members(id, display_name, role, active)
  values ('00000000-0000-0000-0000-000000000c02', 'Access scenario 2', 'administrator', true);
insert into public.staff_accounts
  (staff_member_id, auth_user_id, personal_email, accepted_invite_at)
  values ('00000000-0000-0000-0000-000000000c02', '00000000-0000-0000-0000-000000000b02', 'access-scenario-2@example.test', now());
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000b02","role":"authenticated"}', true);
set local role authenticated;
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a04'), false, 'Administrator: can_edit_section(nights)');
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a05'), false, 'Administrator: can_edit_section(days)');
select is(public.can_edit_schedule(), false, 'Administrator: can_edit_schedule');
select is(public.can_manage_staff(), true, 'Administrator: can_manage_staff');
select is(public.can_manage_unit(), true, 'Administrator: can_manage_unit');
select is(public.can_read_change_log(), true, 'Administrator: can_read_change_log');
select ok((select manager is not distinct from false from public.current_access()), 'Administrator: current_access.manager');
select ok((select administrator is not distinct from true from public.current_access()), 'Administrator: current_access.administrator');
select ok((select maintainer is not distinct from false from public.current_access()), 'Administrator: current_access.maintainer');
select ok((select staff_member_id is not distinct from '00000000-0000-0000-0000-000000000c02'::uuid from public.current_access()), 'Administrator: current_access.staff_member_id');
select ok((select night_scheduler_section_ids is not distinct from '{}'::uuid[] from public.current_access()), 'Administrator: current_access.night_scheduler_section_ids');
select is((select count(*)::integer from public.current_access()), 1, 'Administrator: one Access row');
reset role;
-- Night scheduler for one Section
select set_config('request.jwt.claims', '{}', true);
insert into auth.users(id, email) values ('00000000-0000-0000-0000-000000000b03', 'access-scenario-3@example.test');
insert into public.staff_members(id, display_name, role, active)
  values ('00000000-0000-0000-0000-000000000c03', 'Access scenario 3', 'night_scheduler', true);
insert into public.staff_accounts
  (staff_member_id, auth_user_id, personal_email, accepted_invite_at)
  values ('00000000-0000-0000-0000-000000000c03', '00000000-0000-0000-0000-000000000b03', 'access-scenario-3@example.test', now());
insert into public.night_scheduler_sections(staff_member_id, section_id) values ('00000000-0000-0000-0000-000000000c03', '00000000-0000-0000-0000-000000000a04');
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000b03","role":"authenticated"}', true);
set local role authenticated;
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a04'), true, 'Night scheduler for one Section: can_edit_section(nights)');
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a05'), false, 'Night scheduler for one Section: can_edit_section(days)');
select is(public.can_edit_schedule(), false, 'Night scheduler for one Section: can_edit_schedule');
select is(public.can_manage_staff(), false, 'Night scheduler for one Section: can_manage_staff');
select is(public.can_manage_unit(), false, 'Night scheduler for one Section: can_manage_unit');
select is(public.can_read_change_log(), true, 'Night scheduler for one Section: can_read_change_log');
select ok((select manager is not distinct from false from public.current_access()), 'Night scheduler for one Section: current_access.manager');
select ok((select administrator is not distinct from false from public.current_access()), 'Night scheduler for one Section: current_access.administrator');
select ok((select maintainer is not distinct from false from public.current_access()), 'Night scheduler for one Section: current_access.maintainer');
select ok((select staff_member_id is not distinct from '00000000-0000-0000-0000-000000000c03'::uuid from public.current_access()), 'Night scheduler for one Section: current_access.staff_member_id');
select ok((select night_scheduler_section_ids is not distinct from array['00000000-0000-0000-0000-000000000a04']::uuid[] from public.current_access()), 'Night scheduler for one Section: current_access.night_scheduler_section_ids');
select is((select count(*)::integer from public.current_access()), 1, 'Night scheduler for one Section: one Access row');
reset role;
-- Administrator plus Night scheduler
select set_config('request.jwt.claims', '{}', true);
insert into auth.users(id, email) values ('00000000-0000-0000-0000-000000000b04', 'access-scenario-4@example.test');
insert into public.staff_members(id, display_name, role, active)
  values ('00000000-0000-0000-0000-000000000c04', 'Access scenario 4', 'administrator', true);
insert into public.staff_accounts
  (staff_member_id, auth_user_id, personal_email, accepted_invite_at)
  values ('00000000-0000-0000-0000-000000000c04', '00000000-0000-0000-0000-000000000b04', 'access-scenario-4@example.test', now());
insert into public.night_scheduler_sections(staff_member_id, section_id) values ('00000000-0000-0000-0000-000000000c04', '00000000-0000-0000-0000-000000000a04');
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000b04","role":"authenticated"}', true);
set local role authenticated;
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a04'), true, 'Administrator plus Night scheduler: can_edit_section(nights)');
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a05'), false, 'Administrator plus Night scheduler: can_edit_section(days)');
select is(public.can_edit_schedule(), false, 'Administrator plus Night scheduler: can_edit_schedule');
select is(public.can_manage_staff(), true, 'Administrator plus Night scheduler: can_manage_staff');
select is(public.can_manage_unit(), true, 'Administrator plus Night scheduler: can_manage_unit');
select is(public.can_read_change_log(), true, 'Administrator plus Night scheduler: can_read_change_log');
select ok((select manager is not distinct from false from public.current_access()), 'Administrator plus Night scheduler: current_access.manager');
select ok((select administrator is not distinct from true from public.current_access()), 'Administrator plus Night scheduler: current_access.administrator');
select ok((select maintainer is not distinct from false from public.current_access()), 'Administrator plus Night scheduler: current_access.maintainer');
select ok((select staff_member_id is not distinct from '00000000-0000-0000-0000-000000000c04'::uuid from public.current_access()), 'Administrator plus Night scheduler: current_access.staff_member_id');
select ok((select night_scheduler_section_ids is not distinct from array['00000000-0000-0000-0000-000000000a04']::uuid[] from public.current_access()), 'Administrator plus Night scheduler: current_access.night_scheduler_section_ids');
select is((select count(*)::integer from public.current_access()), 1, 'Administrator plus Night scheduler: one Access row');
reset role;
-- Maintainer without a Repair
select set_config('request.jwt.claims', '{}', true);
insert into auth.users(id, email) values ('00000000-0000-0000-0000-000000000b05', 'access-scenario-5@example.test');
insert into public.staff_members(id, display_name, role, active)
  values ('00000000-0000-0000-0000-000000000c05', 'Access scenario 5', 'staff_member', true);
insert into public.staff_accounts
  (staff_member_id, auth_user_id, personal_email, accepted_invite_at)
  values ('00000000-0000-0000-0000-000000000c05', '00000000-0000-0000-0000-000000000a02', 'access-scenario-5@example.test', now());
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000a02","role":"authenticated"}', true);
set local role authenticated;
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a04'), false, 'Maintainer without a Repair: can_edit_section(nights)');
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a05'), false, 'Maintainer without a Repair: can_edit_section(days)');
select is(public.can_edit_schedule(), false, 'Maintainer without a Repair: can_edit_schedule');
select is(public.can_manage_staff(), false, 'Maintainer without a Repair: can_manage_staff');
select is(public.can_manage_unit(), false, 'Maintainer without a Repair: can_manage_unit');
select is(public.can_read_change_log(), false, 'Maintainer without a Repair: can_read_change_log');
select ok((select manager is not distinct from false from public.current_access()), 'Maintainer without a Repair: current_access.manager');
select ok((select administrator is not distinct from false from public.current_access()), 'Maintainer without a Repair: current_access.administrator');
select ok((select maintainer is not distinct from true from public.current_access()), 'Maintainer without a Repair: current_access.maintainer');
select ok((select staff_member_id is not distinct from '00000000-0000-0000-0000-000000000c05'::uuid from public.current_access()), 'Maintainer without a Repair: current_access.staff_member_id');
select ok((select night_scheduler_section_ids is not distinct from '{}'::uuid[] from public.current_access()), 'Maintainer without a Repair: current_access.night_scheduler_section_ids');
select is((select count(*)::integer from public.current_access()), 1, 'Maintainer without a Repair: one Access row');
reset role;
-- former Manager after handover to Staff member
select set_config('request.jwt.claims', '{}', true);
insert into auth.users(id, email) values ('00000000-0000-0000-0000-000000000b06', 'access-scenario-6@example.test');
insert into public.staff_members(id, display_name, role, active)
  values ('00000000-0000-0000-0000-000000000c06', 'Access scenario 6', 'staff_member', true);
insert into public.staff_accounts
  (staff_member_id, auth_user_id, personal_email, accepted_invite_at)
  values ('00000000-0000-0000-0000-000000000c06', '00000000-0000-0000-0000-000000000b06', 'access-scenario-6@example.test', now());
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000b06","role":"authenticated"}', true);
set local role authenticated;
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a04'), false, 'former Manager after handover to Staff member: can_edit_section(nights)');
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a05'), false, 'former Manager after handover to Staff member: can_edit_section(days)');
select is(public.can_edit_schedule(), false, 'former Manager after handover to Staff member: can_edit_schedule');
select is(public.can_manage_staff(), false, 'former Manager after handover to Staff member: can_manage_staff');
select is(public.can_manage_unit(), false, 'former Manager after handover to Staff member: can_manage_unit');
select is(public.can_read_change_log(), false, 'former Manager after handover to Staff member: can_read_change_log');
select ok((select manager is not distinct from false from public.current_access()), 'former Manager after handover to Staff member: current_access.manager');
select ok((select administrator is not distinct from false from public.current_access()), 'former Manager after handover to Staff member: current_access.administrator');
select ok((select maintainer is not distinct from false from public.current_access()), 'former Manager after handover to Staff member: current_access.maintainer');
select ok((select staff_member_id is not distinct from '00000000-0000-0000-0000-000000000c06'::uuid from public.current_access()), 'former Manager after handover to Staff member: current_access.staff_member_id');
select ok((select night_scheduler_section_ids is not distinct from '{}'::uuid[] from public.current_access()), 'former Manager after handover to Staff member: current_access.night_scheduler_section_ids');
select is((select count(*)::integer from public.current_access()), 1, 'former Manager after handover to Staff member: one Access row');
reset role;
-- revoked or Last-day person
select set_config('request.jwt.claims', '{}', true);
insert into auth.users(id, email) values ('00000000-0000-0000-0000-000000000b07', 'access-scenario-7@example.test');
insert into public.staff_members(id, display_name, role, active)
  values ('00000000-0000-0000-0000-000000000c07', 'Access scenario 7', 'staff_member', false);
insert into public.staff_accounts
  (staff_member_id, auth_user_id, personal_email, accepted_invite_at)
  values ('00000000-0000-0000-0000-000000000c07', '00000000-0000-0000-0000-000000000b07', 'access-scenario-7@example.test', now());
select set_config('request.jwt.claims', '{"sub":"00000000-0000-0000-0000-000000000b07","role":"authenticated"}', true);
set local role authenticated;
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a04'), false, 'revoked or Last-day person: can_edit_section(nights)');
select is(public.can_edit_section('00000000-0000-0000-0000-000000000a05'), false, 'revoked or Last-day person: can_edit_section(days)');
select is(public.can_edit_schedule(), false, 'revoked or Last-day person: can_edit_schedule');
select is(public.can_manage_staff(), false, 'revoked or Last-day person: can_manage_staff');
select is(public.can_manage_unit(), false, 'revoked or Last-day person: can_manage_unit');
select is(public.can_read_change_log(), false, 'revoked or Last-day person: can_read_change_log');
select ok((select manager is not distinct from false from public.current_access()), 'revoked or Last-day person: current_access.manager');
select ok((select administrator is not distinct from false from public.current_access()), 'revoked or Last-day person: current_access.administrator');
select ok((select maintainer is not distinct from false from public.current_access()), 'revoked or Last-day person: current_access.maintainer');
select ok((select staff_member_id is not distinct from null::uuid from public.current_access()), 'revoked or Last-day person: current_access.staff_member_id');
select ok((select night_scheduler_section_ids is not distinct from '{}'::uuid[] from public.current_access()), 'revoked or Last-day person: current_access.night_scheduler_section_ids');
select is((select count(*)::integer from public.current_access()), 1, 'revoked or Last-day person: one Access row');
reset role;
select * from finish();
rollback;
