name: schedule_rules_testing
description: In-memory Schedule stores for tests.
version: 1.0.0
publish_to: none
environment:
  sdk: ^3.13.4
dependencies:
  schedule_rules:
    path: ../schedule_rules
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
