import 'dart:convert';
import 'dart:io';

const maintainerAuth = '00000000-0000-0000-0000-000000000a02';
const nights = '00000000-0000-0000-0000-000000000a04';
const days = '00000000-0000-0000-0000-000000000a05';

String generateAccessScenarios(String fixture) {
  final scenarios = (jsonDecode(fixture) as List<dynamic>)
      .cast<Map<String, dynamic>>();
  final sql = StringBuffer(
    '''-- Generated by packages/schedule_rules/tool/generate_access_scenarios.dart.
-- Edit the JSON scenarios, then regenerate; do not edit this file directly.
begin;
create extension if not exists pgtap with schema extensions;
select plan(${scenarios.length * 12});
insert into auth.users(id, email) values
  ('$maintainerAuth', 'access-scenario-maintainer@example.test');
insert into public.sections(id, name, display_order) values
  ('$nights', 'Access scenario nights', 991),
  ('$days', 'Access scenario days', 992);
insert into private.maintainer_identity(auth_user_id) values ('$maintainerAuth');
''',
  );
  for (final (index, scenario) in scenarios.indexed) {
    final staffAuth =
        '00000000-0000-0000-0000-000000000b${index.toString().padLeft(2, '0')}';
    final staffId =
        '00000000-0000-0000-0000-000000000c${index.toString().padLeft(2, '0')}';
    final name = (scenario['name'] as String).replaceAll("'", "''");
    final manager = scenario['manager'] as bool;
    final administrator = scenario['administrator'] as bool;
    final maintainer = scenario['maintainer'] as bool;
    final repair = scenario['repair'] as bool? ?? false;
    final active = scenario['active'] as bool;
    final sections = (scenario['sections'] as List<dynamic>).cast<String>();
    final role = manager
        ? 'manager'
        : administrator
        ? 'administrator'
        : sections.isNotEmpty
        ? 'night_scheduler'
        : 'staff_member';
    final auth = maintainer ? maintainerAuth : staffAuth;
    final sectionSql = sections.contains('nights')
        ? "insert into public.night_scheduler_sections(staff_member_id, section_id) values ('$staffId', '$nights');\n"
        : '';
    sql.write('''
-- $name
select set_config('request.jwt.claims', '{}', true);
insert into auth.users(id, email) values ('$staffAuth', 'access-scenario-$index@example.test');
insert into public.staff_members(id, display_name, role, active)
  values ('$staffId', 'Access scenario $index', '$role', $active);
insert into public.staff_accounts
  (staff_member_id, auth_user_id, personal_email, accepted_invite_at)
  values ('$staffId', '$auth', 'access-scenario-$index@example.test', now());
$sectionSql''');
    if (repair) {
      sql.writeln(
        "select public.open_maintainer_repair('investigation', null);",
      );
    }
    sql.writeln(
      "select set_config('request.jwt.claims', '{\"sub\":\"$auth\",\"role\":\"authenticated\"}', true);",
    );
    sql.writeln('set local role authenticated;');
    final answers = <String, String>{
      'can_edit_section(nights)': "public.can_edit_section('$nights')",
      'can_edit_section(days)': "public.can_edit_section('$days')",
      'can_edit_schedule': 'public.can_edit_schedule()',
      'can_manage_staff': 'public.can_manage_staff()',
      'can_manage_unit': 'public.can_manage_unit()',
      'can_read_change_log': 'public.can_read_change_log()',
    };
    final expected = <String, bool>{
      'can_edit_section(nights)': scenario['editSection'] as bool,
      'can_edit_section(days)': manager || repair,
      'can_edit_schedule': scenario['runSchedule'] as bool,
      'can_manage_staff': scenario['manageStaff'] as bool,
      'can_manage_unit': scenario['manageUnit'] as bool,
      'can_read_change_log': scenario['readChangeLog'] as bool,
    };
    for (final entry in answers.entries) {
      sql.writeln(
        "select is(${entry.value}, ${expected[entry.key]}, '$name: ${entry.key}');",
      );
    }
    final columns = <String, String>{
      'manager': '$manager',
      'administrator': '$administrator',
      'maintainer': '$maintainer',
      'staff_member_id': scenario['staffMemberId'] == null
          ? 'null::uuid'
          : "'$staffId'::uuid",
      'night_scheduler_section_ids': sections.isEmpty
          ? "'{}'::uuid[]"
          : "array['$nights']::uuid[]",
    };
    for (final entry in columns.entries) {
      sql.writeln(
        "select ok((select ${entry.key} is not distinct from ${entry.value} from public.current_access()), '$name: current_access.${entry.key}');",
      );
    }
    // One assertion for the single-row contract.
    sql.writeln(
      "select is((select count(*)::integer from public.current_access()), 1, '$name: one Access row');",
    );
    sql.writeln('reset role;');
  }
  sql.write('select * from finish();\nrollback;\n');
  return sql.toString();
}

void main() {
  final fixture = File('test/fixtures/access_scenarios.json')
      .readAsStringSync();
  File('../../supabase/tests/database/access_scenarios.test.sql')
      .writeAsStringSync(generateAccessScenarios(fixture));
}
